{% set name = "hpp-manipulation-corba" %}
{% set version = "9.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ab90fba583787d54bdf60e14e5c0604b3f9983ace179fc5f3dcd46f5e31bbb42

build:
  number: 0
  skip: true  # [win or python_impl == 'pypy']
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - libboost-devel
    - tinyxml2
    - urdfdom
    - assimp
    - octomap
    - hpp-fcl
    - qhull
    - qhull-static
    - hpp-util  {{ version }}
    - hpp-statistics  {{ version }}
    - pinocchio
    - hpp-pinocchio  {{ version }}
    - hpp-constraints  {{ version }}
    - hpp-core  {{ version }}
    - hpp-manipulation  {{ version }}
    - hpp-manipulation-urdf  {{ version }}
    - hpp-template-corba  {{ version }}
    - hpp-corbaserver  {{ version }}
    - omniorb
    - omniorbpy
    - python
  run:
    - tinyxml2
    - omniorb
    - omniorbpy
    - numpy
    - python
    - qhull
    - qhull-static

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
